name: plugify
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_otp_text_field: ^1.4.0+2
  google_fonts: ^6.2.1
  standard_searchbar: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/Group 29.png
    - assets/images/Group.png
    - assets/images/Apple.png
    - assets/images/Google.png
    - assets/images/Naija.png
    - assets/images/Check.png
    - assets/images/Group_dark.png
    - assets/images/image1.png
    - assets/images/image2.png
    - assets/images/image3.png
    - assets/images/image4.png
    - assets/images/image5.png
    - assets/images/olamide.png
    - assets/images/Bitmoji.png
    - assets/images/summer.png
    - assets/images/girls.png
    - assets/images/rave.png
    - assets/images/turnfest.png
    - assets/images/bold.png